### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by UMRnInside** [iamanony/b64trans#2]
It's clear that this project is using **LGPL-2.1**
But file _base64.js_ includes:
```
/*
 * $Id: base64.js,v 2.15 2014/04/05 12:58:57 dankogai Exp dankogai $
 *
 *  Licensed under the BSD 3-Clause License.
 *    http://opensource.org/licenses/BSD-3-Clause
 *
 *  References:
 *    http://en.wikipedia.org/wiki/Base64
 */
```

Licensed under the **BSD 3-Clause License.**

**Comment by iamanony** [comment]
Never mind.
it seemed that the 3-clause BSD is not as strict as LGPL v2.1.
